services:
  node:
    build: ./frontend
    ports:
      - 5000:3000
    volumes:
      - ./frontend:/app
  nginx:
    image: nginx:alpine
    ports:
      - 5001:80
    depends_on:
      - php
    volumes:
      - ./api/:/var/www
      - ./containers/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build: ./api
    volumes:
      - ./api/:/var/www
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: CHANGE_ME
      POSTGRES_PASSWORD: admin
      TZ: Europe/Paris
    volumes:
      - postgres:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5002:80
    depends_on:
      - postgres
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_SERVER_JSON_FILE: /pgadminfile/server.json
    volumes:
      - ./containers/pgadmin:/pgadminfile/:ro
    logging:
      driver: none
volumes:
  postgres:
